CONFIG_NAME: 'VAE-ift6135'
DATASET_NAME: SVHN
SEED: 23
IMAGE_SIZE: 32
COMET_ML_UPLOAD: True
# Hyperparameters related to model training
TRAIN:
  DATASET_SPLIT: 'train'
  VALID_SPLIT: 0.1
  TEST_SPLIT: 0.1
  BATCH_SIZE: 100
  NUM_EPOCHS: 50
  MAX_PATIENCE: 10
  LR_SCHEDULER_PARAMS:
    MILESTONES: [80,120]
    GAMMA: 0.1
  NUM_WORKER: 0
MODEL:
  KERNEL_NUM: 10
  CHANNEL_NUM: 3
  LATENT_SIZE: 100
HYPER_PARAMS:
  N_CALLS: 5
  SPACE:
    LR: [0.0001,0.01]
    WEIGHT_DECAY: [0.0001, 0.001]
  INITIAL_VALUES:
    LR: 0.001
    WEIGHT_DECAY: 0.0005

